### ISSUE TITLE
Spartanizer libraries mayhem

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1289]
By @yossigil :
אני חושב שזה קשור לבעית הבניה. כדי לשחזר, בצע זום מלא על הפרויקט, התעלם משגיאות ובצע ספרטניזציה, היא קורסת, ומופיעה ב
ERROR LOG
```
java.io.IOException: Exception in opening zip file: /home/yogi/git/Spartanizer/lib/spartan-1.2.jar
 at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321)
 at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:93)
 at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:106)
 at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65)
 at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:240)
 at org.eclipse.osgi.storage.bundlefile.BundleFile.getResourceURL(BundleFile.java:136)
 at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findResourceImpl(ClasspathManager.java:418)
 at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalResources(ClasspathManager.java:395)
 at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalResources(ModuleClassLoader.java:321)
 at org.eclipse.osgi.internal.loader.BundleLoader.findLocalResources(BundleLoader.java:837)
 at org.eclipse.osgi.internal.loader.BundleLoader.findResources(BundleLoader.java:693)
 at org.eclipse.osgi.internal.loader.ModuleClassLoader.getResources(ModuleClassLoader.java:231)
 at org.eclipse.osgi.internal.framework.ContextFinder.getResources(ContextFinder.java:165)
 at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
 at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
 at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
 at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
 at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
 at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
 at il.org.spartan.plugin.preferences.revision.XMLSpartan.getFileInner(XMLSpartan.java:222)
 at il.org.spartan.plugin.preferences.revision.XMLSpartan.getFile(XMLSpartan.java:202)
 at il.org.spartan.plugin.preferences.revision.XMLSpartan.getTippersByCategories(XMLSpartan.java:90)
 at il.org.spartan.plugin.preferences.revision.XMLSpartan.enabledTippers(XMLSpartan.java:73)
 at il.org.spartan.spartanizer.traversal.Traversal.getPreferredConfiguration(Traversal.java:159)
 at il.org.spartan.spartanizer.traversal.Traversal$2.begin(Traversal.java:50)
 at java.lang.Iterable.forEach(Iterable.java:75)
 at il.org.spartan.spartanizer.traversal.TraversalTappers.begin(TraversalTappers.java:18)
 at il.org.spartan.spartanizer.traversal.Traversal.setCompilationUnit(Traversal.java:186)
 at il.org.spartan.spartanizer.traversal.Traversal.collectTips(Traversal.java:76)
 at il.org.spartan.spartanizer.plugin.Builder.addMarkers(Builder.java:83)
 at il.org.spartan.spartanizer.plugin.Builder.addMarkers(Builder.java:74)
 at il.org.spartan.spartanizer.plugin.Builder.addMarkers(Builder.java:68)
 at il.org.spartan.spartanizer.plugin.Builder.lambda$0(Builder.java:61)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
 at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
 at il.org.spartan.spartanizer.plugin.Builder.incrementalBuild(Builder.java:56)
 at il.org.spartan.spartanizer.plugin.Builder.build(Builder.java:123)
 at il.org.spart

an.spartanizer.plugin.Builder.build(Builder.java:128)
 at il.org.spartan.spartanizer.plugin.Builder.build(Builder.java:100)
 at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
 at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
 at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
 at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
 at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: /home/yogi/git/Spartanizer/lib/spartan-1.2.jar (No such file or directory)
 at java.util.zip.ZipFile.open(Native Method)
 at java.util.zip.ZipFile.<init>(ZipFile.java:219)
 at java.util.zip.ZipFile.<init>(ZipFile.java:149)
 at java.util.zip.ZipFile.<init>(ZipFile.java:163)
 at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304)
 ... 61 more
```

**Comment by OriRoth** [comment]
*What I observed:* it seems like the plugin is looking for `spartan-1.2.jar`, which does not exist anymore. This library is referenced in: `build.properties`, `MANIFEST.MF`, `.classpath`.
*What I checked:* re-cloned the project, problem does not occur. May be local issue.
*What I did:* I recompiled `spartan` and `fluent.ly` into the Spartanizer.
*What I suggest:* delete the project from Eclipse, re-clone and import back to Eclipse.

@ravivos can you check this please? Just follow what Yossi has said:
1. Run the plugin.
2. Open `Error Log` view: `Window -> Show view -> Error Log`.
3. Run zoom on the Spartanizer project, then spartanization.
4. Check for plugin errors in `Error Log` view.

We need this in order to continue working properly.

**Comment by yossigil** [comment]
:100: @AdiOmari
