### ISSUE TITLE
Planting bug:

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#185]
Here is the pertinent information:
```
java.lang.AssertionError: Planting null into ¢ instanceof VariableDeclarationFragment ? this.ctx.getRefactorings() : MISSING/nullreturned null
	at il.org.spartan.spartanizer.assemble.subject$Pair.toCondition(subject.java:266)
	at il.org.spartan.spartanizer.wring.TernaryPushdown.pushdown(TernaryPushdown.java:127)
	at il.org.spartan.spartanizer.wring.TernaryPushdown.pushdown(TernaryPushdown.java:77)
	at il.org.spartan.spartanizer.wring.TernaryPushdown.pushdown(TernaryPushdown.java:31)
	at il.org.spartan.spartanizer.wring.IfExpressionStatementElseSimilarExpressionStatement.replacement(IfExpressionStatementElseSimilarExpressionStatement.java:42)
	at il.org.spartan.spartanizer.wring.IfExpressionStatementElseSimilarExpressionStatement.replacement(IfExpressionStatementElseSimilarExpressionStatement.java:1)
	at il.org.spartan.spartanizer.wring.strategies.ReplaceCurrentNode.claims(ReplaceCurrentNode.java:21)
	at il.org.spartan.spartanizer.wring.dispatch.Toolbox.find(Toolbox.java:187)
	at il.org.spartan.spartanizer.wring.dispatch.Toolbox.find(Toolbox.java:199)
	at il.org.spartan.spartanizer.wring.dispatch.Trimmer$2.go(Trimmer.java:62)
	at il.org.spartan.spartanizer.wring.dispatch.Trimmer$DispatchingVisitor.cautiousGo(Trimmer.java:193)
	at il.org.spartan.spartanizer.wring.dispatch.Trimmer$DispatchingVisitor.visit(Trimmer.java:143)

```

Observe that we have an assertion that produces this.

**Comment by yossigil** [comment]
I think it was produced by
```java
  @Override public boolean visit(final IfStatement node) {
    final BooleanASTMatcher matcher = new BooleanASTMatcher();
    if (match(matcher, node.getThenStatement(), node.getElseStatement())) {
      // Then and else statement are matching, bar the boolean values
      // which are opposite
      final Statement copyStmt = b.copySubtree(node.getThenStatement());
      // identify the node that need to be replaced after the copy
      final BooleanASTMatcher matcher2 = new BooleanASTMatcher(matcher.matches);
      if (match(matcher2, copyStmt, node.getElseStatement())) {
        final Expression ifCondition = node.getExpression();
        copyStmt.accept(new BooleanReplaceVisitor(ifCondition, matcher2.matches.values(), getBooleanName(node)));
        // make sure to keep curly braces if the node is an else statement
        ctx.getRefactorings().replace(node, isElseStatementOfParent(node) ? copyStmt : toSingleStmt(copyStmt));
        return DO_NOT_VISIT_SUBTREE;
      }
    }
    final ReturnStatement thenRs = as(node.getThenStatement(), ReturnStatement.class);
    if (thenRs != null) {
      final Statement elseStmt = node.getElseStatement() != null ? node.getElseStatement() : getNextSibling(node);
      final ReturnStatement elseRs = as(elseStmt, ReturnStatement.class);
      if (elseRs != null)
        return withThenReturnStmt(node, thenRs, elseRs);
      return VISIT_SUBTREE;
    } else
      return noThenReturnStmt(node);
  
```

**Comment by NivShalmon** [comment]
@yossigil where is this visit method defined? I can't find neither it nor the assert that causes this error right now.

**Comment by yossigil** [comment]
This is the input that makes the bug. I took it from AutoRefactor. run the plugin and try to reproduce the bug in interactive setting. If not, maybe  test case?

**Comment by NivShalmon** [comment]
@yossigil does this still happen? I've tried to spartanize this now, and no assertion failed.

**Comment by yossigil** [comment]
Did you try spartanizing AutoRefactor?

**Comment by NivShalmon** [comment]
I'm getting the assertion failure now, but not from the function you wrote above. I'll try to find where it happens and why

**Comment by yossigil** [comment]
Thanks!

**Comment by yossigil** [comment]
I added some printing information
```java
java.lang.AssertionError: BUG:
 x = ¢ instanceof VariableDeclarationFragment ? ctx.getRefactorings().remove(¢.getParent()) : remove(¢.getParent())
 e1 = ctx.getRefactorings().remove(¢.getParent())
 e2 = remove(¢.getParent())
 es1 = [¢.getParent()]
 es2 = [¢.getParent()]
 es1.size() = 1
 es2.size() = 1
 r1 = ctx.getRefactorings()
 r1 = null
-----this is all I know.
	at il.org.spartan.spartanizer.wrings.TernaryPushdown.pushdown(TernaryPushdown.java:138)
	at il.org.spartan.spartanizer.wrings.TernaryPushdown.pushdown(TernaryPushdown.java:79)
	at il.org.spartan.spartanizer.wrings.TernaryPushdown.pushdown(TernaryPushdown.java:32)
	at il.org.spartan.spartanizer.wrings.IfExpressionStatementElseSimilarExpressionStatement.replacement(IfExpressionStatementElseSimilarExpressionStatement.java:43)
	at il.org.spartan.spartanizer.wrings.IfExpressionStatementElseSimilarExpressionStatement.replacement(IfExpressionStatementElseSimilarExpressionStatement.java:1)
	at il.org.spartan.spartanizer.wringing.ReplaceCurrentNode.suggest(ReplaceCurrentNode.java:19)
	at il.org.spartan.spartanizer.wringing.CarefulWring.canSuggest(CarefulWring.java:12)
	at il.org.spartan.spartanizer.wringing.CarefulWring.demandsToSuggestButPerhapsCant(CarefulWring.java:16)
	at il.org.spartan.spartanizer.dispatch.Toolbox.find(Toolbox.java:205)
	at il.org.spartan.spartanizer.dispatch.Toolbox.find(Toolbox.java:217)
	at il.org.spartan.spartanizer.dispatch.Trimmer$2.go(Trimmer.java:84)
	at il.org.spartan.spartanizer.dispatch.DispatchingVisitor.cautiousGo(DispatchingVisitor.java:119)
	at il.org.spartan.spartanizer.dispatch.DispatchingVisitor.visit(DispatchingVisitor.java:53)
	at org.eclipse.jdt.core.dom.IfStatement.accept0(IfStatement.java:187)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:635)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at il.org.spartan.plugin.GUI$Applicator.collectSuggesions(GUI$Applicator.java:113)
	at il.org.spartan.plugin.Builder.addMarkers(Builder.java:77)
	at il.org.spartan.plugin.Builder.addMarkers(Builder.java:72)
	at il.org.spartan.plugin.Builder.addMarkers(Builder.java:56)
	at il.org.spartan.plugin.Builder.lambda$1(Builder.java:100)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at il.org.spartan.plugin.Builder.fullBuild(Builder.java:99)
	at il.org.spartan.plugin.Builder.build(Builder.java:118)
	at il.org.spartan.plugin.Builder.build(Builder.java:91)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at il.org.spartan.plugin.Plugin.refreshAllProjects(Plugin.java:34)
	at il.org.spartan.plugin.Plugin.startSpartan(Plugin.java:63)
	at il.org.spartan.plugin.Plugin.earlyStartup(Plugin.java:74)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:77)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$55.run(Workbench.java:2829)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by NivShalmon** [comment]
I just spartanized autorefactor and the plugin after my last commit and no assertion failures or exceptions happened.It seems this happened because the pushdown assumed only the first reciever can be null (which is true if the trenarization is sorted, since the no receiver method invocation must be the shorter one), but it didn't happen when running the plugin. This does always happen in tests however, so I couldn't write a test for it.
@yossigil can you spartanize autorefactor as well and see if this is solved?

**Comment by yossigil** [comment]
This is not with AutoRefactor. This time I got it with apache common langs.

**Comment by NivShalmon** [comment]
I just spartanized apache common langs as well and no exceptions. @yossigil can you check if these are solved yourself as well?

**Comment by yossigil** [comment]
I think it is working now. No problems for me.
