### ISSUE TITLE
More efficient traversal of compilation units.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#204]
- If no change was made to a compilation unit in a traversal, it should be eliminated from any forthcoming traversals. 
- Apply to entire project, must show much more information.

**Comment by yossigil** [comment]
I think we have a sync/lock problem. Here is some log info:
```
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 95 more
```

!ENTRY org.eclipse.osgi 2 0 2016-09-14 18:25:24.691
!MESSAGE While loading class "il.org.spartan.plugin.Spartanization$1", thread "Thread[main,6,main]" timed out waiting (5002ms) for thread "Thread[Worker-8,5,main]" to finish starting bundle "il.org.spartan.plugin_2.5.0 [522]". To avoid deadlock, thread "Thread[main,6,main]" is proceeding but "il.org.spartan.plugin.Spartanization$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="2.5.0"; osgi.identity="il.org.spartan.plugin"; singleton:="true" [id=522] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:334)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
```

**Comment by yossigil** [comment]
@OriRoth: I think you resolved this. If you did, please close.

**Comment by yossigil** [comment]
:100: 
:+1: 
:+1:
