### ISSUE TITLE
isEmpty bug?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#207]
Here is the error report I got:
```
java.lang.AssertionError: All I know is that threshould=0, and o=>
	at il.org.spartan.spartanizer.wring.InfixComparisonSizeToZero.replacement(InfixComparisonSizeToZero.java:67)
	at il.org.spartan.spartanizer.wring.InfixComparisonSizeToZero.replacement(InfixComparisonSizeToZero.java:63)
	at il.org.spartan.spartanizer.wring.InfixComparisonSizeToZero.replacement(InfixComparisonSizeToZero.java:101)
	at il.org.spartan.spartanizer.wring.InfixComparisonSizeToZero.replacement(InfixComparisonSizeToZero.java:123)
	at il.org.spartan.spartanizer.wring.InfixComparisonSizeToZero.replacement(InfixComparisonSizeToZero.java:1)
	at il.org.spartan.spartanizer.wring.strategies.ReplaceCurrentNode.claims(ReplaceCurrentNode.java:21)
	at il.org.spartan.spartanizer.wring.dispatch.Toolbox.find(Toolbox.java:183)
	at il.org.spartan.spartanizer.wring.dispatch.Toolbox.find(Toolbox.java:195)
	at il.org.spartan.spartanizer.wring.dispatch.Trimmer$2.go(Trimmer.java:62)
```

Note that I added an assertion that prints out the above message.

**Comment by yossigil** [comment]
Try these test cases, if you have a good editor you can convert them into test cases in a snap.
```
list.size() < 2 
j < trace.size()
int x = causeFrames.size() - 1
int x = wrapperFrames.size() - 1
(pos >= x.size()) 
len == x.size() - pos
(pos + ¢ > x.size()) 
int ¢ = x.size() - pos
return pos < x.size();
t = t.t(new String[split.size()])
t = t.t(new String[split.size()])
t = t.t(new Rule[rulesList.size()])
i < t.size()
(i < 0 || i >= collection.size()) 
i(sb.size() + text.length())
final int[] $ = new int[coll.size()];
f(getAllThreads().size() > 0)
f(getAllThreadGroups().size() > 0)
f(getAllThreadGroups().size() >= 7)
f(getAllThreads().size() >= 11)
x(f.size() == f)
x(foundDescriptions.size() == f)
A(typeVarAssigns.size() == 2) 
cs != null ? super.x(cs, offset, count) : super.x(x.buffer, 0, x.size())
```

**Comment by yossigil** [comment]
Also, try this one ` (size() > 0)` with no receiver.

**Comment by yossigil** [comment]
I think the last commit resolved it.
