### ISSUE TITLE
Bug in pushdownTernary

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#247]
!ENTRY org.eclipse.core.resources 4 2 2016-09-22 21:03:06.713
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.AssertionError: BUG: 
 x = "<A HREF=\"" + base_type + ".html\" TARGET=_top>"+ short_type+ "</A>"
 i = 7
 es = ["<A HREF=\"", base_type, ".html\" TARGET=_top>", short_type, "</A>"]
 l = "</A>"
-----this is all I know.
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.replaceSuffix(TernaryPushdownStrings.java:133)
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.simplifyStrings(TernaryPushdownStrings.java:211)
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.simplify(TernaryPushdownStrings.java:144)
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.replacement(TernaryPushdownStrings.java:36)
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.replacement(TernaryPushdownStrings.java:220)
	at il.org.spartan.spartanizer.wrings.TernaryPushdownStrings.replacement(TernaryPushdownStrings.java:1)
	at il.org.spartan.spartanizer.wringing.ReplaceCurrentNode.suggest(ReplaceCurrentNode.java:19)
	at il.org.spartan.spartanizer.wringing.CarefulWring.canSuggest(CarefulWring.java:12)
	at il.org.spartan.spartanizer.dispatch.Toolbox.find(Toolbox.java:206)
	at il.org.spartan.spartanizer.dispatch.Toolbox.find(Toolbox.java:218)
	at il.org.spartan.spartanizer.dispatch.Trimmer$2.go(Trimmer.java:85)

**Comment by yossigil** [comment]
This bug occurs in spartanizing BCEL. 
I think the code is 
```java
    static String referenceType( final String type ) {
		String short_type = Utility.compactClassName(type);
		short_type = Utility.compactClassName(short_type, class_package + ".", true);
		final int index = type.indexOf('[');
		String base_type = type;
		if (index > -1) {
			base_type = type.substring(0, index);
		}
		return basic_types.contains(base_type) ? "<FONT COLOR=\"#00FF00\">" + type + "</FONT>"
				: "<A HREF=\"" + base_type + ".html\" TARGET=_top>" + short_type + "</A>";
	

```

**Comment by yossigil** [comment]
```java
Errors occurred during the build.
Errors running builder 'Spartanizer' on project 'bcel'.
BUG: 
 x = "<A HREF=\"" + base_type + ".html\" TARGET=_top>"+ short_type+ "</A>"
 i = 7
 es = ["<A HREF=\"", base_type, ".html\" TARGET=_top>", short_type, "</A>"]
 l = "</A>"
-----this is all I know.
```
