### ISSUE TITLE
Laconize entire project hangs

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#444]
Here is a dump

``` java
17:30:57.572 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Built project guava in 41 ms
17:30:57.572 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Building project guava-parent
17:30:57.576 [Worker-6] DEBUG o.e.a.i.i.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/yogi/.m2/repository
17:30:57.587 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Built project guava-parent in 14 ms
17:30:58.844 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Building project guava
17:30:58.847 [Worker-6] DEBUG o.e.a.i.i.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/yogi/.m2/repository
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Build participants for MavenProject: com.google.guava:guava:20.0-SNAPSHOT @ /home/yogi/git/guava/guava/pom.xml
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-enforcer-plugin:1.0:enforce (execution: enforce-maven, phase: validate)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: ignore
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-resources-plugin:3.0.1:resources (execution: default-resources, phase: process-resources)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: execute
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (execution: default-compile, phase: compile)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.felix:maven-bundle-plugin:2.5.0:manifest (execution: bundle-manifest, phase: process-classes)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: configurator
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -        Project configurator : id=maven-bundle-plugin class=org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -        Build participant: org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-resources-plugin:3.0.1:testResources (execution: default-testResources, phase: process-test-resources)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: execute
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (execution: default-testCompile, phase: test-compile)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (execution: default-test, phase: test)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.codehaus.mojo:animal-sniffer-maven-plugin:1.14:check (execution: check-java-version-compatibility, phase: test)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: ignore
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.felix:maven-bundle-plugin:2.5.0:bundle (execution: default-bundle, phase: package)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: configurator
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -        Project configurator : id=maven-bundle-plugin class=org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -        Build participant: org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-source-plugin:2.1.2:jar (execution: attach-sources, phase: post-integration-test)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping -    Action: ignore
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-javadoc-plugin:2.8:jar (execution: attach-docs, phase: post-integration-test)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-gpg-plugin:1.4:sign (execution: sign-artifacts, phase: verify)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-install-plugin:2.5.2:install (execution: default-install, phase: install)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.felix:maven-bundle-plugin:2.5.0:install (execution: default-install, phase: install)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (execution: default-deploy, phase: deploy)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.p.c.AbstractCustomizableLifecycleMapping - Mojo execution key: org.apache.felix:maven-bundle-plugin:2.5.0:deploy (execution: default-deploy, phase: deploy)
17:30:58.848 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Executing build participant org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant for plugin execution org.apache.maven.plugins:maven-resources-plugin:3.0.1:resources (execution: default-resources, phase: process-resources)
17:30:58.850 [Worker-6] INFO  o.e.m.c.i.embedder.EclipseLogger - Using 'UTF-8' encoding to copy filtered resources.
17:30:58.860 [Worker-6] INFO  o.e.m.c.i.embedder.EclipseLogger - Copying 0 resource
17:30:58.862 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Finished executing build participant org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant for plugin execution org.apache.maven.plugins:maven-resources-plugin:3.0.1:resources (execution: default-resources, phase: process-resources) in 14 ms
17:30:58.862 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Executing build participant org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1 for plugin execution org.apache.felix:maven-bundle-plugin:2.5.0:manifest (execution: bundle-manifest, phase: process-classes)
17:30:58.863 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Finished executing build participant org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1 for plugin execution org.apache.felix:maven-bundle-plugin:2.5.0:manifest (execution: bundle-manifest, phase: process-classes) in 1 ms
17:30:58.863 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Executing build participant org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant for plugin execution org.apache.maven.plugins:maven-resources-plugin:3.0.1:testResources (execution: default-testResources, phase: process-test-resources)
17:30:58.864 [Worker-6] INFO  o.e.m.c.i.embedder.EclipseLogger - Using 'UTF-8' encoding to copy filtered resources.
17:30:58.864 [Worker-6] INFO  o.e.m.c.i.embedder.EclipseLogger - skip non existing resourceDirectory /home/yogi/git/guava/guava/test
17:30:58.864 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Finished executing build participant org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant for plugin execution org.apache.maven.plugins:maven-resources-plugin:3.0.1:testResources (execution: default-testResources, phase: process-test-resources) in 1 ms
17:30:58.864 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Executing build participant org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1 for plugin execution org.apache.felix:maven-bundle-plugin:2.5.0:bundle (execution: default-bundle, phase: package)
17:30:58.864 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilderImpl - Finished executing build participant org.sonatype.tycho.m2e.felix.internal.MavenBundlePluginConfigurator$1 for plugin execution org.apache.felix:maven-bundle-plugin:2.5.0:bundle (execution: default-bundle, phase: package) in 0 ms
17:30:58.864 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Built project guava in 20 ms
17:30:58.864 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Building project guava-parent
17:30:58.866 [Worker-6] DEBUG o.e.a.i.i.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/yogi/.m2/repository
17:30:58.868 [Worker-6] DEBUG o.e.m.c.i.builder.MavenBuilder - Built project guava-parent in 4 ms
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
    at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
    at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:481)
    at il.org.spartan.plugin.Refactorer.doWork(Refactorer.java:182)
    at il.org.spartan.plugin.Refactorer.go(Refactorer.java:166)
    at il.org.spartan.plugin.Refactorer.run(Refactorer.java:140)
    at org.eclipse.jdt.internal.ui.text.correction.proposals.MarkerResolutionProposal.apply(MarkerResolutionProposal.java:52)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:994)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:938)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$27(CompletionProposalPopup.java:934)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$5.widgetDefaultSelected(CompletionProposalPopup.java:679)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:120)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.AssertionError
    at org.eclipse.jdt.internal.formatter.TokenManager.lastIndexIn(TokenManager.java:205)
    at org.eclipse.jdt.internal.formatter.linewrap.WrapPreparator.prepareElementsList(WrapPreparator.java:834)
    at org.eclipse.jdt.internal.formatter.linewrap.WrapPreparator.visit(WrapPreparator.java:739)
    at org.eclipse.jdt.core.dom.ParameterizedType.accept0(ParameterizedType.java:172)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
    at org.eclipse.jdt.core.dom.ParameterizedType.accept0(ParameterizedType.java:176)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
    at org.eclipse.jdt.core.dom.ClassInstanceCreation.accept0(ClassInstanceCreation.java:311)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
    at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:137)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareWraps(DefaultCodeFormatter.java:380)
    at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:200)
    at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:159)
    at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:142)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatString(ASTRewriteFormatter.java:246)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatNode(ASTRewriteFormatter.java:376)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.getFormattedResult(ASTRewriteFormatter.java:187)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextInsert(ASTRewriteAnalyzer.java:1357)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteMethodBody(ASTRewriteAnalyzer.java:1275)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2059)
    at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:611)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:408)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:446)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:440)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:453)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1702)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:408)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:446)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:440)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:453)
    at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1702)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
    at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:302)
    at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:291)
    at il.org.spartan.plugin.GUI$Applicator.scanCompilationUnit(GUI$Applicator.java:355)
    at il.org.spartan.plugin.GUI$Applicator.scanCompilationUnits(GUI$Applicator.java:389)
    at il.org.spartan.plugin.GUI$Applicator.collectAllTips(GUI$Applicator.java:399)
    at il.org.spartan.plugin.GUI$Applicator.checkFinalConditions(GUI$Applicator.java:61)
    at il.org.spartan.plugin.GUI$Applicator.countTips(GUI$Applicator.java:103)
    at il.org.spartan.plugin.RefactorerUtil$1.run(RefactorerUtil.java:76)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)



```

**Comment by OriRoth** [comment]
The assert that fails:
```
assert tokenInside(node, index);
```
So... it is probably a problem with one of our Tippers.
Now this issue is how do we find what cause it?...
@yossigil what is the project you tried to spartanize? ours? (@sakopzon got stuck while trying to spartanize our project).

**Comment by OriRoth** [comment]
*Updates:*
* Spartanizing JUnit works fine.
* Spartanizing out project get stuck.
* It get stuck while doing tip collection.

**Comment by yossigil** [comment]
guava

**Comment by OriRoth** [comment]
OK I disabled the progress dialog for the tips collection, and now it is working.
I am not sure why it does that - in `Apply to entire project` (single tipper option) something very similar is done with no problems.
@yossigil does it work now? should I investigate more or do we wait for GUI revision?

**Comment by OriRoth** [comment]
You may not believe it, but apparently the problem was.... too long message for progress monitor. The fix was:
```
pm.beginTask("Looking for tips in " + javaProject, IProgressMonitor.UNKNOWN);
```
==>
```
pm.beginTask("Looking for tips in " + javaProject.getElementName(), IProgressMonitor.UNKNOWN);
```
Please tell me if it works now so I can close the issue.

**Comment by OriRoth** [comment]
The code used by ProgressMonitor to shorten the text:
```
	public static String shortenText(String textValue, Control control) {
		if (textValue == null) {
			return null;
		}
		GC gc = new GC(control);
		int maxWidth = control.getBounds().width - 5;
		int maxExtent = gc.textExtent(textValue).x;
		if (maxExtent < maxWidth) {
			gc.dispose();
			return textValue;
		}
		int length = textValue.length();
		int charsToClip = Math.round(0.95f*length * (1 - ((float)maxWidth/maxExtent)));
		int pivot = length / 2;
		int start = pivot - (charsToClip/2);
		int end = pivot + (charsToClip/2) + 1;
		while (start >= 0 && end < length) {
			String s1 = textValue.substring(0, start);
			String s2 = textValue.substring(end, length);
			String s = s1 + ELLIPSIS + s2;
			int l = gc.textExtent(s).x;
			if (l < maxWidth) {
				gc.dispose();
				return s;
			}
			start--;
			end++;
		}
		gc.dispose();
		return textValue;
	}
```

Honestly, I cannot see how it can't go wrong.

**Comment by sakopzon** [comment]
👍

**Comment by yossigil** [comment]
Could it be timing rather than formatting?

**Comment by OriRoth** [comment]
Yes. Maybe I will have to give up the intermediate titles of the progress dialog, i.e. `Spartanizing CU X/Y`.
I investigated similar problems, and this seam to be a very buggy issue...
Also looks like OS related...
I will conduct the changes to the dialogs only after I am sure there is no other solution.

**Comment by yossigil** [comment]
How could it be OS related? Do you say Windows is an O/S?

It only happens in certain tippers, I am investigating these now.

**Comment by yossigil** [comment]
Problems occurs with only certain tippers, if you try to apply them to the entire project
- Tip: Caching pattern: inline into ternary return
- Tip: Merge with subequent 'while', making a 'for (upper=foundIndex; $ < upper;)' loop
- Tip: Remove redundant [final] modifier(s) from declaration
- Tip: Remove redundant else (possibly after inverting if statement)


You can apply each tip individually, it is the batch that's killing it.

**Comment by yossigil** [comment]
It also works in 'apply to compilation unit'

**Comment by OriRoth** [comment]
I did not realized you are talking about `Apply to entire project` and not `Laconize entire project`... but I could not recreate your issue either way, unfortunately.

@yossigil OK I disabled progress dialogs' intermediate messages - any change?

Also this issue being tipper-related is very strange... are you sure it is the case? It really looks like a GUI only issue... any conclusions?

**Comment by yossigil** [comment]
aused by: java.lang.AssertionError: fault: this should not happen! To help you fix the code, here is some info
 counter=3
 u=il.org.spartan.plugin.WrappedCompilationUnit@5de79855
 u.d=[Working copy] FilteredEntryMultimap.java [in com.google.common.collect [in src [in guava]]]
  package com.google.common.collect
  import com.google.common.base.Preconditions.checkNotNull
  import com.google.common.base.Predicates.in
  import com.google.common.base.Predicates.not
  import com.google.common.collect.CollectPreconditions.checkNonnegative
  import com.google.common.annotations.GwtCompatible
  import com.google.common.base.MoreObjects
  import com.google.common.base.Predicate
  import com.google.common.collect.Maps.ViewCachingAbstractMap
  import com.google.j2objc.annotations.WeakOuter
  import java.util.Collection
  import java.util.Collections
  import java.util.Iterator
  import java.util.List
  import java.util.Map
  import java.util.Map.Entry
  import java.util.Set
  import javax.annotation.Nullable
  class FilteredEntryMultimap
    Multimap<K,V> unfiltered
    Predicate<? super Entry<K,V>> predicate
    FilteredEntryMultimap(Multimap<K,V>, Predicate<? super Entry<K,V>>)
    Multimap<K,V> unfiltered()
    Predicate<? super Entry<K,V>> entryPredicate()
    int size()
    boolean satisfies(K, V)
    class ValuePredicate
      K key
      ValuePredicate(K)
      boolean apply(V)
    static Collection<E> filterCollection(Collection<E>, Predicate<? super E>)
    boolean containsKey(Object)
    Collection<V> removeAll(Object)
    Collection<V> unmodifiableEmptyCollection()
    void clear()
    Collection<V> get(K)
    Collection<Entry<K,V>> createEntries()
    Collection<V> createValues()
    Iterator<Entry<K,V>> entryIterator()
    Map<K,Collection<V>> createAsMap()
    Set<K> keySet()
    boolean removeEntriesIf(Predicate<? super Entry<K,Collection<V>>>)
    class AsMap
      boolean containsKey(Object)
      void clear()
      Collection<V> get(Object)
      Collection<V> remove(Object)
      Set<K> createKeySet()
        class KeySetImpl
          KeySetImpl()
          boolean removeAll(Collection<?>)
          boolean retainAll(Collection<?>)
          boolean remove(Object)
      Set<Entry<K,Collection<V>>> createEntrySet()
        class EntrySetImpl
          Map<K,Collection<V>> map()
          Iterator<Entry<K,Collection<V>>> iterator()
            class <anonymous #1>
              Iterator<Entry<K,Collection<V>>> backingIterator
              Entry<K,Collection<V>> computeNext()
          boolean removeAll(Collection<?>)
          boolean retainAll(Collection<?>)
          int size()
      Collection<Collection<V>> createValues()
        class ValuesImpl
          ValuesImpl()
          boolean remove(Object)
          boolean removeAll(Collection<?>)
          boolean retainAll(Collection<?>)
    Multiset<K> createKeys()
    class Keys
      Keys()
      int remove(Object, int)
      Set<Multiset.Entry<K>> entrySet()
        class <anonymous #1>
          Multiset<K> multiset()
          Iterator<Multiset.Entry<K>> iterator()
          int size()
          boolean removeEntriesIf(Predicate<? super Multiset.Entry<K>>)
            class <anonymous #1>
              boolean apply(Map.Entry<K,Collection<V>>)
          boolean removeAll(Collection<?>)
          boolean retainAll(Collection<?>)
 s={526 files, null}
 textchang=org.eclipse.ltk.core.refactoring.TextFileChange@705791af
-----this is all I know.

**Comment by yossigil** [comment]
It only occurs with certain tippers (cannot find where I placed the list), and only if these tippers are applied in batch. It does not matter if it happens in 'Laconize Project' or 'Apply to Project'
