### ISSUE TITLE
Inlining into loops; can tip, but cannot suggest

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#500]
In these example, we get the tip in the problems view as usual, but it cannot be applied

``` java
  void r7(Map<R, V> $) {
     Iterator<Entry<R, V>> iterator = $.entrySet().iterator();
        while (iterator.hasNext()) 
          if (iterator.hashCode() > 12)
              return;
      }  
```

``` java
  void r6(Map<R, V> $) {
     Iterator<Entry<R, V>> iterator = $.entrySet().iterator();
        while (iterator.hasNext()) {
          if (iterator.hashCode() > 12)
              return;
        }
      } 
```

This is the dump

``` java
FAULT: this should not have happened!
-----To help you fix the code, here is some info
 x=java.lang.AssertionError
 counter=12
 u=il.org.spartan.plugin.WrappedCompilationUnit@41a17eaa
 u=StandardTable.java
 textchange=org.eclipse.ltk.core.refactoring.TextFileChange@1dfe6286
 textchange.getEdit.length=null
 textchange.getEdit=nulljava.lang.AssertionError
    at il.org.spartan.spartanizer.utils.fault.done(fault.java:13)
    at il.org.spartan.plugin.GUI$Applicator.apply(GUI$Applicator.java:475)
    at il.org.spartan.plugin.GUI$Applicator.apply(GUI$Applicator.java:451)
    at il.org.spartan.plugin.Spartanizer.lambda$5(Spartanizer.java:135)
    at il.org.spartan.plugin.Spartanizer.lambda$0(Spartanizer.java:49)
    at il.org.spartan.plugin.Spartanizer.lambda$3(Spartanizer.java:115)
    at il.org.spartan.plugin.Spartanizer.go(Spartanizer.java:39)
    at il.org.spartan.plugin.QuickFixer.lambda$0(QuickFixer.java:45)
    at il.org.spartan.plugin.QuickFixer$1.run(QuickFixer.java:93)
    at org.eclipse.jdt.internal.ui.text.correction.proposals.MarkerResolutionProposal.apply(MarkerResolutionProposal.java:52)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:994)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:938)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.verifyKey(CompletionProposalPopup.java:1388)
    at org.eclipse.jface.text.contentassist.ContentAssistant$InternalListener.verifyKey(ContentAssistant.java:803)
    at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:485)
    at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1134)
    at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6044)
    at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5733)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1378)
    at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:764)
    at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3457)
    at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:801)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2000)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5819)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5490)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9555)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4141)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

-----this is all I know.
```

**Comment by OriRoth** [comment]
No good @yossigil, this dump does not show the original failed assert, only your artificial `fault.unreachable()`. Do you think there is a chance for `x.printStackTrace`?

**Comment by yossigil** [comment]
I made a collection of examples in the main folder, with a bunch of files from `guava`

**Comment by OriRoth** [comment]
See commit above. Created directory `laconization-cases-results` containing spartanized finles from `laconization-cases`. Placed `//XXX: spartanized` near spartanized code. If you prefer I can spartanize `lacoinnzation-cases` itself so you will be able to compare changes using git compare.

@yossigil Can you spartanize those files now? Are there any spartanization suggestions that you expected but did not appear?

**Comment by OriRoth** [comment]
BTW you cannot spartanize `laconizaion-cases` as a folder, you'll need to spartanize each file by text selection (i.e. `ctrl+a` then `ctrl+alt+s` or button). See #507

**Comment by yossigil** [comment]
Good job.  I am busy with travel, year start, etc., so won't be able to attend to this now.

**Comment by yossigil** [comment]
Defunct with the highlight mechanism
