### ISSUE TITLE
TableReusabilityIndices throws exception when it does not find Java files in a directory

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/Spartanizer#962]
The Exception is the following:

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:500)
	at java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
	at il.org.spartan.spartanizer.cmdline.TableReusabilityIndices.summarize(TableReusabilityIndices.java:180)
	at il.org.spartan.spartanizer.cmdline.TableReusabilityIndices.done(TableReusabilityIndices.java:134)
	at il.org.spartan.spartanizer.cmdline.FolderASTVisitor.visit(FolderASTVisitor.java:76)
	at il.org.spartan.spartanizer.cmdline.FolderASTVisitor.visit(FolderASTVisitor.java:54)
	at il.org.spartan.spartanizer.cmdline.FolderASTVisitor.main(FolderASTVisitor.java:48)
	at il.org.spartan.spartanizer.cmdline.TableReusabilityIndices.main(TableReusabilityIndices.java:29)
```

**Comment by M4tt30rru** [comment]
Done
