### ISSUE TITLE
Spartanizer crashes

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#982]
When I load the project, with the existing spartanizer plugin from the market place, Eclipse cannot build it, yielding this message
```java
org.eclipse.core.runtime.CoreException: Plug-in il.org.spartan.plugin was unable to load class il.org.spartan.plugin.Builder.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:902)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:855)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:547)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:576)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle il.org.spartan.plugin (466).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:116)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:291)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:286)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$55.run(Workbench.java:2829)
	... 1 more
Caused by: org.osgi.framework.BundleException: Exception in il.org.spartan.plugin.Plugin.start() of bundle il.org.spartan.plugin.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:795)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	... 20 more
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: Current builder: org.eclipse.pde.internal.core.builders.ManifestConsistencyChecker, new builder: org.eclipse.pde.internal.core.builders.ManifestConsistencyChecker, configuration: il.org.spartan.plugin; []
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
	at org.eclipse.core.internal.events.BuildCommand.addBuilder(BuildCommand.java:244)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:551)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:576)
	at org.eclipse.core.internal.events.BuildManager.getRule(BuildManager.java:1122)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:545)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at il.org.spartan.plugin.old.RefreshAll.go(RefreshAll.java:19)
	at il.org.spartan.plugin.Plugin.startSpartan(Plugin.java:29)
	at il.org.spartan.plugin.Plugin.start(Plugin.java:50)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	... 27 more
```

**Comment by yossigil** [comment]
The main error is : `Plug-in il.org.spartan.plugin was unable to load class il.org.spartan.plugin.Plugin.`

**Comment by OriRoth** [comment]
@yossigil can you send me your `BuildCommand.java` file? It is located in *plugins* directory. On my machine the path is:
```
plugins\org.eclipse.core.resources.source_3.11.0.v20160503-1608.jar\org\eclipse\core\internal\events
```

**Comment by OriRoth** [comment]
@yossigil it seams like a problem in `RefreshAll`. I inspected `org.eclipse.core.internal.events.BuildCommand` and concluded there may be a collision with another plugin's build (or with itself??).

**Comment by yossigil** [comment]
OK. So, how do I fix it? 
(Remember, I am now a client...)

**Comment by OriRoth** [comment]
When exception is thrown:
* click OK
* click your project in package explorer, then type `ctrl+4`, wait a second or so then type `ctrl+4` again.

We will make an effort to fix the problem ASAP and will post here a reference to a patch when it would be available.

**Comment by yossigil** [comment]
Doing this, I get this in the error log: `Invalid input url:platform:/plugin/org.eclipse.team.cvs.ui/icons/full/wizban/createpatch_wizban.png`
